---
- name: Install python-software-properties for BB repo
  apt: name=python-software-properties state=present

- name: Add brightbox repository
  apt_repository: repo=ppa:brightbox/ruby-ng update_cache=yes

- name: Install Ruby 2.1
  apt: name=ruby2.1 state=present

- name: Install Ruby development headers
  apt: name=ruby2.1-dev state=present

- name: Install Bundler
  command: gem install bundler